services:
  mysql:
    image: mysql:8.3.0
    restart: always
    container_name: mysql
    hostname: mysql-hostname
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./volumes/mysql_data:/var/lib/mysql
    ports:
      - 3306:3306

  redis:
    image: redis:latest
    container_name: redis
    hostname: redis-hostname
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./volumes/redis_data:/data

  rabbitmq:
    image: rabbitmq:management
    restart: always
    container_name: rabbitmq
    hostname: rabbitmq-hostname
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./volumes/rabbitmq_data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    depends_on:
      - redis
      - mysql

  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    container_name: qdrant
    hostname: qdrant-hostname
    ports:
      - 6333:6333
      - 6334:6334
    volumes:
      - ./volumes/qdrant_data/storage:/qdrant/storage
      - ./volumes/qdrant_data/snapshots:/qdrant/snapshots
      - ./volumes/qdrant_data/config:/qdrant/config
      - ./qdrant_config.yaml:/qdrant/config/production.yaml
    environment:
      - QDRANT__SERVICE__API_KEY=${QDRANT_API_KEY}

  whisper:
    image: onerahmet/openai-whisper-asr-webservice:latest
    restart: always
    container_name: whisper
    hostname: whisper-hostname
    environment:
      - ASR_MODEL=base
      - ASR_ENGINE=openai_whisper
    ports:
      - 9000:9000

  minio:
    image: minio/minio
    container_name: minio
    hostname: minio-hostname
    ports:
      - "19000:9000"
      - "19001:9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    volumes:
      - ./volumes/minio_data:/data
    command: server /data --console-address ":9001"

  celery:
    image: lago-celery:0.01
    restart: always
    container_name: celery
    hostname: celery-hostname
    environment:
      - USING_PROXY=${USING_PROXY}
      - PROXY_URL=${PROXY_URL}
      - LAGO_MYSQL_HOST=mysql
      - LAGO_MYSQL_DB=${LAGO_MYSQL_DB}
      - LAGO_MYSQL_USERNAME=${LAGO_MYSQL_USERNAME}
      - LAGO_MYSQL_PASSWORD=${LAGO_MYSQL_PASSWORD}
      - LAGO_RABBITMQ_HOST=rabbitmq
      - LAGO_RABBITMQ_API_PORT=5672
      - LAGO_RABBITMQ_USER=${RABBITMQ_DEFAULT_USER}
      - LAGO_RABBITMQ_PASS=${RABBITMQ_DEFAULT_PASS}
      - QDRANT_HOST=http://qdrant:6333
      - QDRANT_API_KEY=${QDRANT_API_KEY}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LANGCHAIN_TRACING_V2=${LANGCHAIN_TRACING_V2}
      - LANGCHAIN_ENDPOINT=${LANGCHAIN_ENDPOINT}
      - LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY}
      - WHISPER_HOST=whisper
      - WHISPER_PORT=9000
      - MINIO_ENDPOINT=minio
      - MINIO_PORT=9000
      - MINIO_USE_SSL=${MINIO_USE_SSL}
      - MINIO_ACCESS_KEY=${MINIO_ROOT_USER}
      - MINIO_SECRET_KEY=${MINIO_ROOT_PASSWORD}
      - MINIO_BUCKET=${MINIO_BUCKET}
      - MINIO_BUCKET_TTS=${MINIO_BUCKET_TTS}
      - TTS_HOST_URL=${TTS_HOST_URL}
    volumes:
      # - ./api:/app:ro # Bind mount the source code directory (read-only)
      - ./volumes/celery_logs:/var/log/celery # Volume for logs
      - ./volumes/celery_data:/app/cache
    depends_on:
      - rabbitmq
      - redis
  jervis:
    build:
      context: ./
      dockerfile: Dockerfile
    # image: jervis-tetch:0.01
    restart: always
    container_name: jervis
    hostname: jervis-hostname
    ports:
      - 3000:3000
    environment:
      - LAGO_BASE_URL=http://lago:8088
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_API_PORT=${RABBITMQ_API_PORT}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - SECRET_KEY=${SECRET_KEY}
      - MYSQL_HOST=mysql
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MINIO_ENDPOINT=minio
      - MINIO_PORT=9000
      - MINIO_USE_SSL=${MINIO_USE_SSL}
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_BUCKET=${MINIO_BUCKET}
    depends_on:
      - rabbitmq
      - redis
      - whisper
      - qdrant
      - celery
      - mysql
