services:
  rabbitmq:
    image: rabbitmq:management
    restart: always
    container_name: rabbitmq
    hostname: rabbitmq-hostname
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./volumes/rabbitmq_data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}

  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    container_name: qdrant
    hostname: qdrant-hostname
    ports:
      - 6333:6333
      - 6334:6334
    volumes:
      - ./volumes/qdrant_data/storage:/qdrant/storage
      - ./volumes/qdrant_data/snapshots:/qdrant/snapshots
      - ./volumes/qdrant_data/config:/qdrant/config
      - ./qdrant_config.yaml:/qdrant/config/production.yaml
    environment:
      - QDRANT__SERVICE__API_KEY=${QDRANT_API_KEY}

  mysql:
    image: mysql:8.3.0
    restart: always
    container_name: mysql
    hostname: mysql-hostname
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./volumes/mysql_data:/var/lib/mysql
    ports:
      - 3306:3306

  whisper:
    image: onerahmet/openai-whisper-asr-webservice:latest
    restart: always
    container_name: whisper
    hostname: whisper-hostname
    environment:
      - ASR_MODEL=base
      - ASR_ENGINE=openai_whisper
    ports:
      - 9000:9000

  lago:
    image: lago:0.01
    restart: always
    container_name: lago
    hostname: lago-hostname
    ports:
      - 8088:8088
    depends_on:
      - rabbitmq
      - qdrant
      - mysql
      - whisper
    volumes:
      - ./volumes/lago_data:/app/cache
      - shared_volume_lago_jervis:/app/uploads
    environment:
      - RUNNING_ENV=docker-compose
      - QDRANT_HOST=http://qdrant:6333
      - QDRANT_API_KEY=${QDRANT_API_KEY}
      - LAGO_MYSQL_HOST=mysql
      - LAGO_MYSQL_DB=${LAGO_MYSQL_DB}
      - LAGO_MYSQL_USERNAME=${LAGO_MYSQL_USERNAME}
      - LAGO_MYSQL_PASSWORD=${LAGO_MYSQL_PASSWORD}
      - LAGO_RABBITMQ_HOST=rabbitmq
      - LAGO_RABBITMQ_USER=${LAGO_RABBITMQ_USER}
      - LAGO_RABBITMQ_PASS=${LAGO_RABBITMQ_PASS}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - WHISPER_HOST=whisper

  jervis:
    image: jervis-tetch:0.01
    restart: always
    container_name: jervis
    hostname: jervis-hostname
    ports:
      - 3000:3000
    depends_on:
      - lago
    environment:
      - LAGO_BASE_URL=http://lago:8088
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - shared_volume_lago_jervis:/usr/src/app/uploads
volumes:
  shared_volume_lago_jervis: